repos:
  - repo: local
    hooks:
      - id: bikeshed-build
        name: check bikeshed files build
        entry: bikeshed update && bikeshed spec
        language: python
        types: [file]
        files: \.bs$
        additional_dependencies: ['bikeshed']

