name: Auto Deployment
on:
  push:
    branches: [master]
    paths: ["src/**"]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: src/operator-question-mark.bs
          DESTINATION: operator-question-mark/index.html
          VALIDATE_LINKS: true
          VALIDATE_MARKUP: true
          GH_PAGES_BRANCH: gh-pages
